version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: employee-db
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - employee-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/employee_db
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - employee-network

volumes:
  db-data:

networks:
  employee-network:
